@startuml

class Ball
class Barrier
class Brick
class Brinck_Braker 
class GraphicsRunner
class Musica
class Paddle
class StageBuilder

Brinck_Braker *-- Ball
Brinck_Braker *-- Paddle
Brinck_Braker *-- Brick
Brinck_Braker *-- Barrier
Brinck_Braker *-- Musica

Brinck_Braker o-- GraphicsRunner
Brinck_Braker o-- StageBuilder

Paddle o-- Ball

Brick --|> Barrier


@enduml