@startuml Brinck_Braker
Sam
class Ball
class Barrier
class Brick
class Brinck_Braker 
class GraphicsRunner
class Paddle
class StageBuilder

Brinck_Braker "1" *-- "*" Ball
Brinck_Braker "1" *-- "1" Paddle
Brinck_Braker "1" *-- "*" Brick
Brinck_Braker "1 "*--  "*" Barrier

Brinck_Braker "1" o-- "1" GraphicsRunner
Brinck_Braker "1" o-- "1 +"StageBuilder

Paddle "1" o-- "*" Ball

Brick --|> Object


@enduml